name: Push to Ec2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_KEY }}
          REMOTE_HOST: ${{ secrets.SSH }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.PWD }}
